/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// `Env` (Worker bindings: ASSETS, SESSION, CMDK_KV, CMDK_RATE_LIMITER, +
// anything added to wrangler.jsonc) and the `cloudflare:workers` module are
// typed by worker-configuration.d.ts, generated by `wrangler types` (npm run
// cf-typegen / postinstall). Don't hand-roll them — add bindings to
// wrangler.jsonc and regenerate. Route code deliberately re-types the bindings
// it uses as OPTIONAL structural interfaces (see CmdkEnv in api/cmdk.ts):
// dev/tests run without the real bindings, so every route degrades gracefully.

// Astro 7 + CF adapter v14: `Astro.locals` exposes `cfContext` (ExecutionContext,
// for waitUntil). The legacy `locals.runtime.env` was removed — read env via
// `import { env } from 'cloudflare:workers'` instead.
type CloudflareRuntime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  interface Locals extends CloudflareRuntime {}
}

// Public, build-time-inlined env vars (PUBLIC_ prefix only).
interface ImportMetaEnv {
  readonly PUBLIC_SANITY_PROJECT_ID: string;
  readonly PUBLIC_SANITY_DATASET: string;
  readonly PUBLIC_SANITY_API_VERSION: string;
  readonly PUBLIC_GA_MEASUREMENT_ID: string;
  readonly PUBLIC_TURNSTILE_SITE_KEY: string;
  readonly PUBLIC_CMDK_TURNSTILE_SITE_KEY?: string;
  readonly PUBLIC_FORMSPREE_URL?: string;
  readonly PUBLIC_HCAPTCHA_SITEKEY?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Cloudflare Turnstile global (loaded via the api.js script tag), used by the
// CommandPalette (interaction-only) island. The ContactForm island uses
// hCaptcha + Formspree instead (see HCaptchaApi below).
interface TurnstileApi {
  render(
    el: HTMLElement | string,
    opts: {
      sitekey: string;
      theme?: 'auto' | 'light' | 'dark';
      size?: 'normal' | 'compact' | 'flexible';
      execution?: 'render' | 'execute';
      appearance?: 'always' | 'execute' | 'interaction-only';
      action?: string;
      callback?: (token: string) => void;
      'expired-callback'?: () => void;
      'timeout-callback'?: () => void;
      'error-callback'?: (errorCode?: string) => void;
    },
  ): string;
  reset(id?: string): void;
  remove(id?: string): void;
  execute(el?: HTMLElement | string, opts?: { callback?: (token: string) => void }): void;
  getResponse(id?: string): string | undefined;
}

// hCaptcha global (loaded via api.js?render=explicit), used by the ContactForm
// island. The token is verified by Formspree server-side — no Worker involved.
interface HCaptchaApi {
  render(
    el: HTMLElement | string,
    opts: {
      sitekey: string;
      theme?: 'light' | 'dark';
      size?: 'normal' | 'compact' | 'invisible';
      callback?: (token: string) => void;
      'expired-callback'?: () => void;
      'error-callback'?: (errorCode?: string) => void;
    },
  ): string;
  reset(id?: string): void;
  remove(id?: string): void;
  getResponse(id?: string): string | undefined;
}

interface Window {
  turnstile?: TurnstileApi;
  hcaptcha?: HCaptchaApi;
}
