/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

// `Env` (Worker bindings: ASSETS, SESSION, + anything added to wrangler.jsonc)
// and the `cloudflare:workers` module are typed by worker-configuration.d.ts,
// generated by `wrangler types` (npm run cf-typegen / postinstall). Don't
// hand-roll them — add bindings to wrangler.jsonc and regenerate.

// Astro 7 + CF adapter v14: `Astro.locals` exposes `cfContext` (ExecutionContext,
// for waitUntil). The legacy `locals.runtime.env` was removed — read env via
// `import { env } from 'cloudflare:workers'` instead.
type CloudflareRuntime = import('@astrojs/cloudflare').Runtime;

declare namespace App {
  interface Locals extends CloudflareRuntime {}
}

// Public, build-time-inlined env vars (PUBLIC_ prefix only).
interface ImportMetaEnv {
  readonly PUBLIC_SANITY_PROJECT_ID: string;
  readonly PUBLIC_SANITY_DATASET: string;
  readonly PUBLIC_SANITY_API_VERSION: string;
  readonly PUBLIC_GA_MEASUREMENT_ID: string;
  readonly PUBLIC_TURNSTILE_SITE_KEY: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
